[data]

# This will run on the 5th, 11th, 36th, 41st, and 57th second of every minute
[data.interval]
[data.interval.jobs]
[data.interval.jobs."test_cron"]
schedule = "5,11,36,41,57 * * * * * *"
log_type = "test_cron"

# [data.websocket]
# [data.websocket.websockets]
# [data.websocket."websockets"."demo_rpc_call"]
# log_type = "testing"
# [data.websocket."websockets"."demo_rpc_call".uris]
# simplystaking = "wss://some_websocket"
# [data.websocket."websockets"."demo_rpc_call".message_config]
# message = "{ \"id\": 1, \"jsonrpc\": \"2.0\", \"method\": \"eth_getBlockByNumber\", \"params\": [ \"finalized\", false ]}"
# sleep_duration = 100 ## This means the message is sent every 0.1 seconds
# [data.websocket."websockets"."demo_rpc_call"."headers"]

# [data.github]
# org = ""
# log_type = "Web" # Can be one of Web, Git, All

# Authentication using FPAT
# [data.github.authentication]
# token = ""

# Authentication using GitHub App Creds
## [data.github.authentication]
## app_id = 1234
## installation_id = 1234
## private_key = ""
