[storage.shared_dbs."shared_db_1"]
size_limit = { Limited = 50 }
r = ["test_shared_db_rule_1.wasm"]
rw = ["test_shared_db_rule_2.wasm"]

[storage.db]
sled_path = "/tmp/sled"

# [storage.db]
# table_name = "test-plaid"

# [storage.db.authentication]
# access_key_id = "value here"
# secret_access_key = "value here"
# session_token = "value here"
# region = "value here"
