[webhooks."internal"]
listen_address = "0.0.0.0:4554"

# Webhooks for tests
[webhooks."internal".webhooks."timetest"]
log_type = "time"
headers = []

[webhooks."internal".webhooks."persistentresponsetest"]
log_type = "prtest"
logbacks_allowed = "Unlimited"
headers = ["x-forwarded-for"]
[webhooks."internal".webhooks."persistentresponsetest".get_mode]
response_mode = "rule:test_persistent_response.wasm"
[webhooks."internal".webhooks."persistentresponsetest".get_mode.caching_mode]
type = "None"

[webhooks."internal".webhooks."testsshcerts"]
log_type = "test_sshcerts"
headers = []
[webhooks."internal".webhooks."testsshcerts".get_mode]
response_mode = "rule:test_sshcerts_usage.wasm"
[webhooks."internal".webhooks."testsshcerts".get_mode.caching_mode]
type = "None"

[webhooks."internal".webhooks."crashtest"]
log_type = "crashtest"
headers = []

[webhooks."internal".webhooks."testlogback"]
log_type = "test_logback"
logbacks_allowed = { Limited = 1 }
headers = []
[webhooks."internal".webhooks."testlogback".get_mode]
response_mode = "rule:test_logback.wasm"
[webhooks."internal".webhooks."testlogback".get_mode.caching_mode]
type = "None"

[webhooks."internal".webhooks."testdb"]
log_type = "test_db"
headers = []

[webhooks."internal".webhooks."testfileopen"]
log_type = "test_fileopen"
headers = []

[webhooks."internal".webhooks."testshareddb_1"]
log_type = "test_shareddb_1"
headers = []

[webhooks."internal".webhooks."testshareddb_2"]
log_type = "test_shareddb_2"
headers = []

[webhooks."internal".webhooks."testrandom"]
log_type = "test_random"
headers = []

[webhooks."internal".webhooks."testmnr"]
log_type = "test_mnr"
headers = []

[webhooks."internal".webhooks."testregex"]
log_type = "test_regex"
headers = []


[webhooks."internal".webhooks."examplegithub_graphql"]
log_type = "none"
headers = ["Authorization"]
[webhooks."internal".webhooks."examplegithub_graphql".get_mode]
response_mode = "rule:example_github_graphql.wasm"
[webhooks."internal".webhooks."examplegithub_graphql".get_mode.caching_mode]
# Note that this needs to be none as any other value will cause a security issue. This is because
# caching is handled at the runtime level, thus not giving the rule a chance to deny returning
# the cached data.
type = "None"


[webhooks."internal".webhooks."testgeteverything"]
log_type = "test_geteverything"
headers = ["Authorization", "my_secret"]
[webhooks."internal".webhooks."testgeteverything".get_mode]
response_mode = "rule:test_get_everything.wasm"
[webhooks."internal".webhooks."testgeteverything".get_mode.caching_mode]
type = "None"

[webhooks."internal".webhooks."testmode"]
log_type = "testmode"
headers = []

[webhooks."internal".webhooks."testslack"]
log_type = "test_slack"
headers = []

# End webhooks for tests

# Additional webhook examples
[webhooks."internal".webhooks."FFFFA"]
log_type = "testing"
headers = ["x-forwarded-for"]
[webhooks."internal".webhooks."FFFFA".get_mode]
response_mode = "static:this is just static data to return to the caller"

[webhooks."internal".webhooks."LOADTEST1"]
log_type = "testing"
headers = ["notalegitheader", "reallynotlegit"]

[webhooks."internal".webhooks."LOADTEST2"]
log_type = "testing2"
headers = ["notalegitheader", "reallynotlegit"]

[webhooks."internal".webhooks."LOADTEST4"]
log_type = "testing4"
headers = ["notalegitheader", "reallynotlegit"]

[webhooks."internal".webhooks."FFFFB"]
log_type = "testing"
headers = ["x-forwarded-for"]
[webhooks."internal".webhooks."FFFFB".get_mode]
response_mode = "rule:testing_test.wasm"
[webhooks."internal".webhooks."FFFFB".get_mode.caching_mode]
type = "Timed"
validity = 10

[webhooks."external"]
listen_address = "0.0.0.0:4556"
[webhooks."external".webhooks."AAAA"]
log_type = "testing"
headers = ["notalegitheader", "reallynotlegit"]
[webhooks."external".webhooks."AAAA".get_mode]
response_mode = "facebook:somelongstring"
