#!/bin/bash

set -e

# Define what webhook within Plaid we're going to call
URL="testsshcerts"

DATA="VGhpcyBpcyBhIFBsYWlkIHRlc3Q="
SIGNATURE="LS0tLS1CRUdJTiBTU0ggU0lHTkFUVVJFLS0tLS0KVTFOSVUwbEhBQUFBQVFBQUFFb0FBQUFhYzJzdGMzTm9MV1ZrTWpVMU1UbEFiM0JsYm5OemFDNWpiMjBBQUFBZ1J0SFBHYwoxWDhDMVQ3UXpBRTR0bGZCa2VpN2FvSk9jeGMwd0JHM2JmVWVrQUFBQUVjM05vT2dBQUFBcHdiR0ZwWkMxMFpYTjBBQUFBCkFBQUFBQVp6YUdFMU1USUFBQUJuQUFBQUduTnJMWE56YUMxbFpESTFOVEU1UUc5d1pXNXpjMmd1WTI5dEFBQUFRSFlpYnMKOG53QlRpdFowYWl3UVlEbXpzWEZUMEg3bDdmUTQ5QmVJTTdMR25IWnd0R1lMN2Rza2hLT01yYUdiR0lQR2tKUXJ4WUYvSwptSUNRM0xqbnhnNEJBQUFBRFE9PQotLS0tLUVORCBTU0ggU0lHTkFUVVJFLS0tLS0="

# Call the webhook
OUTPUT=$(curl -XGET http://$PLAID_LOCATION/webhook/$URL?signature=$SIGNATURE\&data=$DATA)

if [[ $OUTPUT == *"OK"* ]]; then
  exit 0
fi
echo "Could not validate signature against the rule: $OUTPUT"
exit 1