name: Dependency Minimum Age Check

on:
  pull_request:

jobs:
  runtime:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: read

    steps:
      - name: Check for relevant changes
        id: filter
        uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706 # v4.0.2
        with:
          filters: |
            relevant:
              - "runtime/Cargo.lock"

      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install Rust
        if: steps.filter.outputs.relevant == 'true'
        uses: actions-rs/toolchain@b2417cde72dcf67f306c0ae8e0828a81bf0b189f # v1.0.6
        with:
          toolchain: stable
          override: true

      - uses: timweri/cargo-oxidate@49d33667fb3a743822022e05c60f911ee255e0f7 # v0.1.8
        if: steps.filter.outputs.relevant == 'true'
        with:
          cargo-lock-path: runtime/Cargo.lock
          min-age-days: 14
          suggest-fix: true
