name: Docker Checks

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches:  "**"

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  ubuntu-docker-build-musl-amd64:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          runtime/target/
        key: ${{ runner.os }}-cargo-amd64-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Run Docker Build Test (amd64)
      run: cd runtime && docker build -t latest -f plaid/resources/docker/musl/Dockerfile.amd64 .


  ubuntu-docker-build-musl-aarch64:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          runtime/target/
        key: ${{ runner.os }}-cargo-aarch64-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Run Docker Build Test (aarch64)
      run: cd runtime && docker build -t latest -f plaid/resources/docker/musl/Dockerfile.aarch64 .

  ubuntu-docker-build-llvm:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          runtime/target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Run Docker Build Test (llvm)
      run: cd runtime && docker build -t latest -f plaid/resources/docker/Dockerfile . --build-arg FEATURES=llvm


  ubuntu-docker-build-llvm-cross:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          runtime/target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Run Docker Build Test (llvm)
      run: |
        sudo apt update && \ 
        sudo apt-get upgrade -y && \
        cd runtime && docker buildx build --platform linux/amd64,linux/arm64 -t plaid:0.22.0 -f plaid/resources/docker/Dockerfile  . --build-arg FEATURES=llvm --load

  