name: DynamoDB for Rules Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches:  "**"

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always
  # fake for AWS CLI to local dynamo container
  AWS_ACCESS_KEY_ID: test123 
  AWS_SECRET_ACCESS_KEY: test123 
  AWS_DEFAULT_REGION: us-east-1
  TABLE_NAME: local_test


jobs:
  ubuntu-cranelift:
    runs-on: ubuntu-latest
    services:
      dynamodb:
        image: amazon/dynamodb-local:latest
        ports:
          - 8000:8000

    steps:
    # - name: Setup Rust
    #   run: |
    #     rustup toolchain install nightly-2024-12-14  # pinning the nightly version should help with caching dependencies
    #     rustup default nightly-2024-12-14
    #     rustup target add wasm32-unknown-unknown
    #
    # - uses: actions/checkout@v4

    # - uses: actions/cache@v4
    #   with:
    #     path: |
    #       ~/.cargo/bin/
    #       ~/.cargo/registry/index/
    #       ~/.cargo/registry/cache/
    #       ~/.cargo/git/db/
    #       runtime/target/
    #       modules/target/
    #     key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: List Tables 
      run: aws dynamodb list-tables --endpoint-url http://localhost:8000

    - name: create Tables 
      run: |
        aws dynamodb create-table \
          --table-name $TABLE_NAME \
          --attribute-definitions \
              AttributeName=pk,AttributeType=S \
              AttributeName=timestamp,AttributeType=S \
          --key-schema \
              AttributeName=pk,KeyType=HASH \
              AttributeName=timestamp,KeyType=RANGE \
          --billing-mode PAY_PER_REQUEST \
          --endpoint-url http://localhost:8000 

    - name: List Tables 
      run: aws dynamodb list-tables --endpoint-url http://localhost:8000 

    - name: delete table
      run: |
        aws dynamodb delete-table \
          --table-name $TABLE_NAME \
          --endpoint-url http://localhost:8000

    - name: List Tables 
      run: aws dynamodb list-tables --endpoint-url http://localhost:8000 
  # ubuntu-llvm:
  #   runs-on: ubuntu-latest
  #
  #   steps:
  #   - name: Setup Rust
  #     run: |
  #       rustup toolchain install nightly-2024-12-14  # pinning the nightly version should help with caching dependencies
  #       rustup default nightly-2024-12-14
  #       rustup target add wasm32-unknown-unknown
  #       sudo apt install -y libllvm18 llvm-18 llvm-18-dev llvm-18-runtime libpolly-18-dev libclang-common-18-dev
  #
  #   - uses: actions/checkout@v4
  #
  #   - uses: actions/cache@v4
  #     with:
  #       path: |
  #         ~/.cargo/bin/
  #         ~/.cargo/registry/index/
  #         ~/.cargo/registry/cache/
  #         ~/.cargo/git/db/
  #         runtime/target/
  #         modules/target/
  #       key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
  #
  #   - name: Run Integration Tests on LLVM
  #     run: ./testing/integration.sh llvm
