name: Release secrets manager

on:
  workflow_call:

permissions:
  contents: write

jobs:
  release_secrets_manager:
    name: Release secrets manager
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build secrets manager for aarch64
        run: |
          cd runtime
          docker build -t secrets_manager -f plaid/resources/Dockerfile_secrets_manager.aarch64 .
          # By default, this container prints the base64 encoding of the executable.
          # We take it and pipe-decode it into a file, which will then be released.
          docker run --rm secrets_manager | base64 -d > secrets_manager

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: secrets_manager
          path: runtime/secrets_manager
