name: Release secrets manager

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release_secrets_manager:
    name: Release secrets manager
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            runtime/target/
          key: ${{ runner.os }}-cargo-secretsmanager-${{ hashFiles('**/Cargo.lock') }}

      - name: Build secrets manager
        run: cd runtime && cargo build --bin=secrets_manager --release

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: runtime/target/release/secrets_manager
