"test-secret" = "This is a test secret"
"public-key" = "{CI_PUBLIC_KEY_PLACEHOLDER}"
"test-webhook-secret" = "{CI_SLACK_TEST_WEBHOOK}"
"test-slack-bot-token" = "{CI_SLACK_TEST_BOT_TOKEN}"
"integration-test-root-ca" = """{CI_CERTIFICATE_PLACEHOLDER}"""
"example-auth-token" = "475e52cf9c4c1a62e1de7392598d42bab026b5cd2d86bfa33cfb9716de958739"
