FROM messense/rust-musl-cross:aarch64-musl

RUN mkdir /build
WORKDIR /build
COPY . .

RUN cargo build --release --bin=secrets_manager

ENTRYPOINT ["/usr/bin/base64", "-w0", "target/aarch64-unknown-linux-musl/release/secrets_manager"]
